blueprint:
  name: lampu
  description: LAMP
  icon: 
    file : redstone.png
    content : (--- base64 encoded ---)
  # by default, it should refer to our forj web documentation, to present the blueprint documentation. But we can propose to change it.
  documentation : 'http://openstack.org/forj'
  locations:
    modules: 
      - src-repo: lampu
        git: https://github.com/daihaojun/lampu
        install:
          puppet-apply: install
        uninstall:
          puppet-apply: uninstall
      - src-repo: php
        git: https://github.com/thias/puppet-php.git        
        puppet-extra-modules: /opt/config/production/git/php/
        src-repo: jenkins
        git: https://github.com/jenkinsci/puppet-jenkins.git
        puppet-extra-modules: /opt/config/production/git/jenkins/